/* ══════════════════════════════════════════════════════════════════════════════
   ALL 15 BEHAVIORAL SCENARIOS — dashboard mock data
   Each scenario shows its most dramatic / story-telling week as "current".
   ══════════════════════════════════════════════════════════════════════════════ */

export const SCENARIOS = [
  /* ── 1. THE DUNNING SPIRAL ────────────────────────────────────────────────── */
  {
    id: "dunning_spiral",
    label: "The Dunning Spiral",
    description: "Recurring payment failures, recovery playbook, double-cycle pattern",
    badge: "churn",
    data: {
      reporting_week: "2026-W08",
      last_run: "2026-02-19T09:00:00Z",
      mrr: { current: 5050, previous: 4850, change_pct: 4.12 },
      active_subscriptions: 46,
      churn: { rate: 0.0, at_risk: 0, reason: "Second dunning cycle resolved via direct outreach. All accounts current." },
      velocity: { opened: 13, closed: 12, net: 1, avg_close_hrs: 35.0, backlog: 38 },
      blocked: [],
      confidence: { current: 0.81, history: [0.72, 0.70, 0.65, 0.68, 0.76, 0.68, 0.63, 0.81] },
      red_flags: [],
      skills: [
        { name: "saas_metrics_dashboard", tier: 0, agent: "CFO", status: "healthy", success_rate: 100 },
        { name: "dunning_recovery_playbook", tier: 1, agent: "CEO", status: "healthy", success_rate: 80 },
        { name: "github_issue_auto_triage", tier: 1, agent: "PM", status: "healthy", success_rate: 95 },
        { name: "weekly_digest_delivery", tier: 1, agent: "CEO", status: "healthy", success_rate: 100 },
      ],
      digests: [
        { period: "2026-W08", status: "delivered", channel: "slack" },
        { period: "2026-W07", status: "delivered", channel: "email" },
        { period: "2026-W06", status: "delivered", channel: "slack" },
      ],
      cost: { last_run: 0.00034, monthly: 0.014, ceiling: 25.0 },
      recommendation: "Second dunning cycle resolved. 3 accounts recovered via personal outreach. Pattern confirmed: dunning recurs every ~5 weeks. Recommend automated payment-method-update nudge at day 3 of failed payment to prevent third cycle.",
      advisor_note: "This is the second dunning spiral in 8 weeks (W2-4, W6-8). Pattern: payment failures cluster in 3-week cycles then clear. W7 matches W3 escalation signature. Recommend quarterly dunning prevention review targeting onboarding cohorts.",
      advisor_confidence: 0.81,
      playbook_match: { name: "Dunning Recovery", success_rate: 0.80, applications: 4, flag: "strong" },
      unit_economics: { rule40_score: 22.1, health_grade: "Adequate", ltv_simple: 1260, arpu: 109.8, quick_ratio: 2.1, nrr_pct: 98.4 },
      triage: { total: 13, categories: { bug: 3, feature: 4, chore: 4, question: 2 }, priorities: { P0: 0, P1: 1, P2: 5, P3: 7 }, pending_review: 2 },
      audit_events: [
        { event_type: "RUN_COMPLETE", severity: "info", message: "Weekly run W08 completed. MRR: $5,050 (+4.1%).", created_at: "2026-02-19T09:01:12Z" },
        { event_type: "OUTCOME_RECORDED", severity: "info", message: "W07 dunning outreach → 3 accounts recovered ($600/mo).", created_at: "2026-02-19T09:01:10Z" },
        { event_type: "ADVISOR_MATCH", severity: "info", message: "Playbook: Dunning Recovery (80%, 4 runs). Second cycle confirmed.", created_at: "2026-02-19T09:01:09Z" },
        { event_type: "CONFIDENCE_RECORDED", severity: "info", message: "CEO confidence: 0.81 (recovery from W07 low of 0.63).", created_at: "2026-02-19T09:01:08Z" },
        { event_type: "MEMORY_WRITTEN", severity: "info", message: "Memory page: 2026-W08 Dunning Spiral Recovery (3 chunks).", created_at: "2026-02-19T09:01:06Z" },
      ],
      deltas: { mrr_pct: 4.12, velocity_net: 1, backlog_delta: -1, confidence_delta: 0.18 },
      saved_mrr: {
        direct: { amount: 600, actions: 2, avg_confidence: 0.92 },
        likely: { amount: 250, actions: 2, avg_confidence: 0.71 },
        reported: { amount: 0, actions: 0, avg_confidence: null },
      },
      memory_health: { total_pages: 8, matches_found: 3, avg_relevance: 0.84, active_playbooks: 2, stale_playbooks: 0 },
      llm_provider: "Gemini 2.5 Flash",
      cross_model_consistency: 91,
    },
    memoryPages: [
      { id: "d-w08", title: "2026-W08 Operational Report", category: "retention", tags: ["mrr-growth", "playbook:Dunning Recovery"], compiled_truth: "MRR rose 4.1% to $5,050. 46 active subscriptions. Second dunning cycle resolved. 3 accounts recovered. Confidence: 0.81.", created_at: "2026-02-19T09:01:06Z", metadata: { reporting_week: "2026-W08", confidence: 0.81 }, timeline: [{ event: "OUTCOME_RECORDED", detail: "3 dunning accounts recovered ($600/mo)." }] },
      { id: "d-w07", title: "2026-W07 Operational Report", category: "churn_prevention", tags: ["churn", "red-flags", "playbook:Dunning Recovery"], compiled_truth: "MRR declined 3.0% to $4,850. 44 subs. 4 accounts in dunning — mirrors W2-4 pattern. Confidence: 0.63. Risk escalation: W7 matches W3 signature.", created_at: "2026-02-12T09:01:06Z", metadata: { reporting_week: "2026-W07", confidence: 0.63 }, timeline: [{ event: "RISK_ESCALATION", detail: "Dunning spiral cycle 2 confirmed — matches W3 pattern." }] },
      { id: "d-w06", title: "2026-W06 Operational Report", category: "churn_prevention", tags: ["churn"], compiled_truth: "MRR declined 1.96% to $5,000. New dunning cycle begins — different accounts, same pattern as W1-3.", created_at: "2026-02-05T09:01:06Z", metadata: { reporting_week: "2026-W06", confidence: 0.68 }, timeline: [{ event: "CEO_RECOMMEND", detail: "Dunning Recovery playbook: second cycle activation." }] },
      { id: "d-w05", title: "2026-W05 Operational Report", category: "retention", tags: ["mrr-growth"], compiled_truth: "MRR rose 3.0% to $5,100. All dunning cleared — first cycle resolved. 2 upgrades. Confidence: 0.76.", created_at: "2026-01-29T09:01:06Z", metadata: { reporting_week: "2026-W05", confidence: 0.76 }, timeline: [{ event: "RUN_COMPLETE", detail: "First dunning cycle cleared." }] },
      { id: "d-w04", title: "2026-W04 Operational Report", category: "churn_prevention", tags: ["churn", "playbook:Dunning Recovery"], compiled_truth: "MRR rose 1.0% to $4,950. Recovery underway — 2 accounts still in dunning. Confidence: 0.68.", created_at: "2026-01-22T09:01:06Z", metadata: { reporting_week: "2026-W04", confidence: 0.68 }, timeline: [{ event: "ADVISOR_MATCH", detail: "Dunning Recovery playbook: 60% recovery rate so far." }] },
      { id: "d-w03", title: "2026-W03 Operational Report", category: "churn_prevention", tags: ["churn", "red-flags"], compiled_truth: "MRR declined 2.97% to $4,900. 4 accounts in dunning — payments failed 2x+. Playbook triggered.", created_at: "2026-01-15T09:01:06Z", metadata: { reporting_week: "2026-W03", confidence: 0.65 }, timeline: [{ event: "CEO_RECOMMEND", detail: "Dunning Recovery playbook activated. Prioritise accounts >$100/mo." }] },
    ],
    attributionEntries: [
      { id: "da1", week: "2026-W08", attribution_tier: "direct", mrr_amount: 600, action_id: "da-w08-d1", evidence: { confidence: 0.92, action: "3 dunning accounts recovered via personal outreach", playbook: "Dunning Recovery" } },
      { id: "da2", week: "2026-W05", attribution_tier: "direct", mrr_amount: 450, action_id: "da-w05-d1", evidence: { confidence: 0.89, action: "2 dunning accounts recovered (first cycle)", playbook: "Dunning Recovery" } },
      { id: "da3", week: "2026-W05", attribution_tier: "likely", mrr_amount: 200, action_id: "da-w05-l1", evidence: { confidence: 0.68, action: "2 new subs onboarded week following recovery" } },
    ],
  },

  /* ── 2. THE VELOCITY CRASH ─────────────────────────────────────────────────── */
  {
    id: "velocity_crash",
    label: "The Velocity Crash",
    description: "Engineering slowdown triggers churn — cross-signal escalation at W4",
    badge: "engineering",
    data: {
      reporting_week: "2026-W04",
      last_run: "2026-01-22T09:00:00Z",
      mrr: { current: 11300, previous: 11700, change_pct: -3.42 },
      active_subscriptions: 87,
      churn: { rate: 0.04, at_risk: 8, reason: "Critical: 8 accounts at churn risk — engineering velocity at 6-month low. Unresolved bugs directly cited in cancellation requests." },
      velocity: { opened: 24, closed: 4, net: 20, avg_close_hrs: 96.0, backlog: 93 },
      blocked: [
        { id: "GH-301", title: "Payment gateway timeout under load", since: "2026-01-12", reason: "Waiting for infrastructure team capacity" },
        { id: "GH-318", title: "API rate limiter misconfiguration", since: "2026-01-19", reason: "DevOps ticket open — no ETA" },
      ],
      confidence: { current: 0.61, history: [0.79, 0.72, 0.66, 0.61] },
      red_flags: [
        { metric: "Engineering Velocity", severity: "critical", detail: "4 issues closed vs 24 opened this week. Backlog at 93 — 6-month high." },
        { metric: "Churn Risk", severity: "critical", detail: "8 accounts at risk. Unresolved bugs cited in 3 cancellation emails this week." },
      ],
      skills: [
        { name: "saas_metrics_dashboard", tier: 0, agent: "CFO", status: "healthy", success_rate: 100 },
        { name: "github_issue_auto_triage", tier: 1, agent: "PM", status: "failing", success_rate: 62 },
        { name: "velocity_drop_alert", tier: 1, agent: "PM", status: "healthy", success_rate: 88 },
        { name: "weekly_digest_delivery", tier: 1, agent: "CEO", status: "healthy", success_rate: 100 },
      ],
      digests: [
        { period: "2026-W04", status: "delivered", channel: "slack" },
        { period: "2026-W03", status: "delivered", channel: "email" },
      ],
      cost: { last_run: 0.00041, monthly: 0.017, ceiling: 25.0 },
      recommendation: "ESCALATION: Two independent signals — velocity crash + churn spike. Backlog at 93 (6-month high). 4 issues closed vs 24 opened. Unblock GH-301 (payment gateway) immediately — directly blocking 3 enterprise upgrades and cited in cancellation emails. Engineering lead must triage top-10 customer-impacting bugs by EOD.",
      advisor_note: "Cross-signal escalation confirmed: velocity crash (W2) + churn spike (W3-4) = 2 independent signals. Matches W3 precedent where backlog growth preceded churn by 1 week. Recovery estimate: 3-4 weeks if blockers cleared now.",
      advisor_confidence: 0.61,
      playbook_match: { name: "Velocity Drop Alert", success_rate: 0.72, applications: 3, flag: "strong" },
      unit_economics: { rule40_score: -8.4, health_grade: "Critical", ltv_simple: 2260, arpu: 129.9, quick_ratio: 0.9, nrr_pct: 91.2 },
      triage: { total: 24, categories: { bug: 14, feature: 4, chore: 4, question: 2 }, priorities: { P0: 2, P1: 8, P2: 10, P3: 4 }, pending_review: 6 },
      audit_events: [
        { event_type: "RISK_ESCALATION", severity: "critical", message: "W04 escalation: velocity crash + churn spike (2 independent signals).", created_at: "2026-01-22T09:01:12Z" },
        { event_type: "RED_FLAG_RAISED", severity: "critical", message: "Engineering velocity at 6-month low. 2 P0 issues unresolved >5 days.", created_at: "2026-01-22T09:01:11Z" },
        { event_type: "ADVISOR_MATCH", severity: "warning", message: "Playbook: Velocity Drop Alert (72%, 3 runs). Escalation pathway active.", created_at: "2026-01-22T09:01:10Z" },
        { event_type: "CONFIDENCE_RECORDED", severity: "warning", message: "CEO confidence dropped to 0.61 — lowest in 4-week run.", created_at: "2026-01-22T09:01:08Z" },
        { event_type: "MEMORY_WRITTEN", severity: "info", message: "Memory page: 2026-W04 Velocity Crash Escalation (4 chunks).", created_at: "2026-01-22T09:01:06Z" },
      ],
      deltas: { mrr_pct: -3.42, velocity_net: 20, backlog_delta: 20, confidence_delta: -0.05 },
      saved_mrr: { direct: { amount: 0, actions: 0, avg_confidence: null }, likely: { amount: 0, actions: 0, avg_confidence: null }, reported: { amount: 0, actions: 0, avg_confidence: null } },
      memory_health: { total_pages: 4, matches_found: 2, avg_relevance: 0.77, active_playbooks: 1, stale_playbooks: 0 },
      llm_provider: "Gemini 2.5 Flash",
      cross_model_consistency: 88,
    },
    memoryPages: [
      { id: "vc-w04", title: "2026-W04 Velocity Crash Escalation", category: "engineering", tags: ["low-velocity", "churn", "red-flags"], compiled_truth: "MRR declined 3.42% to $11,300. 87 active subs. 8 accounts at churn risk. Velocity: 4 closed / 24 opened. 2 P0 blockers. ESCALATION triggered — 2 independent signals. Confidence: 0.61.", created_at: "2026-01-22T09:01:06Z", metadata: { reporting_week: "2026-W04", confidence: 0.61 }, timeline: [{ event: "RISK_ESCALATION", detail: "Velocity crash + churn spike — 2 independent signals." }, { event: "RED_FLAG_RAISED", detail: "GH-301 and GH-318 blocking enterprise upgrades." }] },
      { id: "vc-w03", title: "2026-W03 Operational Report", category: "churn_prevention", tags: ["churn", "low-velocity"], compiled_truth: "MRR declined 3.31% to $11,700. 91 subs. 5 accounts at risk. Backlog at 73. Velocity Drop Alert playbook triggered.", created_at: "2026-01-15T09:01:06Z", metadata: { reporting_week: "2026-W03", confidence: 0.66 }, timeline: [{ event: "CEO_RECOMMEND", detail: "Velocity Drop Alert: backlog growth + first churn signals." }] },
      { id: "vc-w02", title: "2026-W02 Operational Report", category: "engineering", tags: ["low-velocity"], compiled_truth: "MRR rose 0.83% to $12,100. 95 subs. Velocity dropped: 9 closed / 20 opened. Avg close time 48h. Playbook triggered.", created_at: "2026-01-08T09:01:06Z", metadata: { reporting_week: "2026-W02", confidence: 0.72 }, timeline: [{ event: "CEO_RECOMMEND", detail: "Velocity Drop Alert: first signal — backlog growing." }] },
      { id: "vc-w01", title: "2026-W01 Operational Report", category: "reporting", tags: ["mrr-growth"], compiled_truth: "MRR rose 1.69% to $12,000. 95 subs. Healthy baseline. Velocity strong: 15 closed / 18 opened.", created_at: "2026-01-01T09:01:06Z", metadata: { reporting_week: "2026-W01", confidence: 0.79 }, timeline: [{ event: "RUN_COMPLETE", detail: "Healthy baseline established." }] },
    ],
    attributionEntries: [],
  },

  /* ── 3. THE GROWTH ROCKET ──────────────────────────────────────────────────── */
  {
    id: "growth_rocket",
    label: "The Growth Rocket",
    description: "Rapid MRR expansion — feature triage, activation bottleneck detection",
    badge: "growth",
    data: {
      reporting_week: "2026-W05",
      last_run: "2026-01-29T09:00:00Z",
      mrr: { current: 6000, previous: 4500, change_pct: 33.33 },
      active_subscriptions: 63,
      churn: { rate: 0.0, at_risk: 0, reason: "Growth phase peak — no churn indicators. 15 new accounts this week." },
      velocity: { opened: 40, closed: 35, net: 5, avg_close_hrs: 26.0, backlog: 43 },
      blocked: [],
      confidence: { current: 0.84, history: [0.71, 0.76, 0.80, 0.82, 0.84] },
      red_flags: [],
      skills: [
        { name: "saas_metrics_dashboard", tier: 0, agent: "CFO", status: "healthy", success_rate: 100 },
        { name: "feature_request_triage", tier: 1, agent: "PM", status: "healthy", success_rate: 94 },
        { name: "github_issue_auto_triage", tier: 1, agent: "PM", status: "healthy", success_rate: 97 },
        { name: "weekly_digest_delivery", tier: 1, agent: "CEO", status: "healthy", success_rate: 100 },
      ],
      digests: [
        { period: "2026-W05", status: "delivered", channel: "slack" },
        { period: "2026-W04", status: "delivered", channel: "email" },
      ],
      cost: { last_run: 0.00038, monthly: 0.016, ceiling: 25.0 },
      recommendation: "Growth peak: +33% MRR in one week, 15 new accounts. Feature Request Triage playbook active — backlog at 43 driven by feature demand. Prioritise top-5 feature requests by subscriber count. Activation rate is critical: ensure all new accounts complete onboarding within 48h or risk W8-W9 churn cohort.",
      advisor_note: "Growth trajectory matches top-quartile PLG patterns. Feature demand backlog growing proportionally with new users — healthy signal. Monitor activation: rapid growth cohorts show 30-day lag before churn risk materialises. Run activation audit on W2-W3 cohorts now.",
      advisor_confidence: 0.84,
      playbook_match: { name: "Feature Request Triage", success_rate: 0.82, applications: 2, flag: "strong" },
      unit_economics: { rule40_score: 61.3, health_grade: "Excellent", ltv_simple: 1800, arpu: 95.2, quick_ratio: 8.4, nrr_pct: 112.0 },
      triage: { total: 40, categories: { bug: 4, feature: 24, chore: 8, question: 4 }, priorities: { P0: 0, P1: 2, P2: 18, P3: 20 }, pending_review: 8 },
      audit_events: [
        { event_type: "RUN_COMPLETE", severity: "info", message: "Weekly run W05 completed. MRR: $6,000 (+33.3%). 15 new accounts.", created_at: "2026-01-29T09:01:12Z" },
        { event_type: "ADVISOR_MATCH", severity: "info", message: "Feature Request Triage: 24 feature issues this week — 60% of backlog.", created_at: "2026-01-29T09:01:10Z" },
        { event_type: "CONFIDENCE_RECORDED", severity: "info", message: "CEO confidence: 0.84 (growth phase peak).", created_at: "2026-01-29T09:01:08Z" },
        { event_type: "SLACK_SENT", severity: "info", message: "W05 digest posted to #all-ai-ops-dogfood.", created_at: "2026-01-29T09:01:06Z" },
      ],
      deltas: { mrr_pct: 33.33, velocity_net: 5, backlog_delta: 5, confidence_delta: 0.02 },
      saved_mrr: { direct: { amount: 0, actions: 0, avg_confidence: null }, likely: { amount: 800, actions: 2, avg_confidence: 0.72 }, reported: { amount: 400, actions: 1, avg_confidence: null } },
      memory_health: { total_pages: 5, matches_found: 2, avg_relevance: 0.88, active_playbooks: 2, stale_playbooks: 0 },
      llm_provider: "Gemini 2.5 Flash",
      cross_model_consistency: 93,
    },
    memoryPages: [
      { id: "gr-w05", title: "2026-W05 Growth Peak Report", category: "expansion", tags: ["mrr-growth", "feature-demand"], compiled_truth: "MRR rose 33.3% to $6,000. 63 subs. 15 new accounts. Feature Request Triage triggered — 24 feature issues. Confidence: 0.84.", created_at: "2026-01-29T09:01:06Z", metadata: { reporting_week: "2026-W05", confidence: 0.84 }, timeline: [{ event: "ADVISOR_MATCH", detail: "Feature Request Triage: 24 feature issues, 60% of backlog." }] },
      { id: "gr-w04", title: "2026-W04 Operational Report", category: "expansion", tags: ["mrr-growth", "feature-demand"], compiled_truth: "MRR rose 32.4% to $4,500. 48 subs. 12 new accounts. Feature backlog at 38 — triage playbook first triggered.", created_at: "2026-01-22T09:01:06Z", metadata: { reporting_week: "2026-W04", confidence: 0.82 }, timeline: [{ event: "CEO_RECOMMEND", detail: "Feature Request Triage first activation." }] },
      { id: "gr-w03", title: "2026-W03 Operational Report", category: "expansion", tags: ["mrr-growth"], compiled_truth: "MRR rose 30.8% to $3,400. 36 subs. 9 new accounts. Rapid growth continuing. No churn signals.", created_at: "2026-01-15T09:01:06Z", metadata: { reporting_week: "2026-W03", confidence: 0.80 }, timeline: [{ event: "RUN_COMPLETE", detail: "Rapid growth phase continuing." }] },
    ],
    attributionEntries: [
      { id: "gr-a1", week: "2026-W05", attribution_tier: "likely", mrr_amount: 800, action_id: "gr-w05-l1", evidence: { confidence: 0.72, action: "Onboarding sequence improved — higher activation rate correlated" } },
      { id: "gr-a2", week: "2026-W05", attribution_tier: "operator_reported", mrr_amount: 400, action_id: "gr-w05-r1", evidence: { action: "2 referrals from accounts that received weekly digest" } },
    ],
  },

  /* ── 4. THE SILENT CHURN ───────────────────────────────────────────────────── */
  {
    id: "silent_churn",
    label: "The Silent Churn",
    description: "cancel_at_period_end detected before revenue drops — pre-churn signal",
    badge: "churn",
    data: {
      reporting_week: "2026-W04",
      last_run: "2026-01-22T09:00:00Z",
      mrr: { current: 23500, previous: 24900, change_pct: -5.62 },
      active_subscriptions: 28,
      churn: { rate: 0.10, at_risk: 2, reason: "3 pending cancels executed ($1,400 MRR lost). 2 more in billing queue. Early detection at W2 gave 2-week intervention window." },
      velocity: { opened: 6, closed: 5, net: 1, avg_close_hrs: 48.0, backlog: 18 },
      blocked: [],
      confidence: { current: 0.67, history: [0.78, 0.74, 0.70, 0.67] },
      red_flags: [
        { metric: "Silent Churn Execution", severity: "critical", detail: "$1,400 MRR lost as predicted W2. 2 more pending cancels in billing queue." },
      ],
      skills: [
        { name: "saas_metrics_dashboard", tier: 0, agent: "CFO", status: "healthy", success_rate: 100 },
        { name: "pre_churn_signal", tier: 1, agent: "CEO", status: "healthy", success_rate: 76 },
        { name: "github_issue_auto_triage", tier: 1, agent: "PM", status: "healthy", success_rate: 95 },
      ],
      digests: [
        { period: "2026-W04", status: "delivered", channel: "slack" },
        { period: "2026-W03", status: "delivered", channel: "email" },
      ],
      cost: { last_run: 0.00036, monthly: 0.015, ceiling: 25.0 },
      recommendation: "ESCALATION: Silent churn executed — $1,400 MRR lost from 3 accounts that set cancel_at_period_end at W2. 2 more cancels in queue. Activate win-back outreach for the 3 departed accounts. Intervene on 2 remaining pending cancels within 24h. Root cause: billing friction + lack of perceived value at 30-day mark.",
      advisor_note: "Pre-churn signal detected at W2 (2 weeks before revenue drop at W4) — system correctly identified cancel_at_period_end before execution. Second cluster appearing at W5 — matches W2 pattern. Recommend adding proactive success check-in at day 25 of billing cycle.",
      advisor_confidence: 0.67,
      playbook_match: { name: "Pre-Churn Signal", success_rate: 0.76, applications: 3, flag: "moderate" },
      unit_economics: { rule40_score: -12.2, health_grade: "Critical", ltv_simple: 6900, arpu: 839.3, quick_ratio: 0.6, nrr_pct: 86.4 },
      triage: { total: 6, categories: { bug: 1, feature: 2, chore: 2, question: 1 }, priorities: { P0: 0, P1: 1, P2: 3, P3: 2 }, pending_review: 1 },
      audit_events: [
        { event_type: "RISK_ESCALATION", severity: "critical", message: "W04 escalation: $1,400 MRR lost + 2 more pending cancels (2 independent signals).", created_at: "2026-01-22T09:01:12Z" },
        { event_type: "RED_FLAG_RAISED", severity: "critical", message: "Silent churn executed: 3 cancel_at_period_end accounts terminated billing.", created_at: "2026-01-22T09:01:11Z" },
        { event_type: "ADVISOR_MATCH", severity: "warning", message: "Pre-Churn Signal playbook: W2 detection confirmed accurate — 2-week lead time.", created_at: "2026-01-22T09:01:09Z" },
        { event_type: "MEMORY_WRITTEN", severity: "info", message: "Memory page: 2026-W04 Silent Churn Execution (3 chunks).", created_at: "2026-01-22T09:01:06Z" },
      ],
      deltas: { mrr_pct: -5.62, velocity_net: 1, backlog_delta: 0, confidence_delta: -0.03 },
      saved_mrr: { direct: { amount: 0, actions: 0, avg_confidence: null }, likely: { amount: 0, actions: 0, avg_confidence: null }, reported: { amount: 0, actions: 0, avg_confidence: null } },
      memory_health: { total_pages: 4, matches_found: 2, avg_relevance: 0.81, active_playbooks: 1, stale_playbooks: 0 },
      llm_provider: "Gemini 2.5 Flash",
      cross_model_consistency: 86,
    },
    memoryPages: [
      { id: "sc-w04", title: "2026-W04 Silent Churn Execution", category: "churn_prevention", tags: ["churn", "mrr-decline", "red-flags"], compiled_truth: "MRR declined 5.62% to $23,500. 28 subs. 3 pending cancels executed ($1,400 lost). 2 more in queue. ESCALATION triggered. System predicted this at W2.", created_at: "2026-01-22T09:01:06Z", metadata: { reporting_week: "2026-W04", confidence: 0.67 }, timeline: [{ event: "RISK_ESCALATION", detail: "Silent churn executed — predicted 2 weeks earlier." }] },
      { id: "sc-w03", title: "2026-W03 Operational Report", category: "churn_prevention", tags: ["churn"], compiled_truth: "MRR declined 0.40% to $24,900. 4 accounts with pending cancellation — billing period ending. Pre-Churn Signal active.", created_at: "2026-01-15T09:01:06Z", metadata: { reporting_week: "2026-W03", confidence: 0.70 }, timeline: [{ event: "CEO_RECOMMEND", detail: "4 accounts pending cancel — outreach window closing." }] },
      { id: "sc-w02", title: "2026-W02 Silent Churn Detected", category: "churn_prevention", tags: ["churn"], compiled_truth: "MRR flat at $25,000. 3 accounts set cancel_at_period_end — MRR still intact but revenue loss in 2-3 weeks. Pre-Churn Signal playbook triggered. W2 detection = 2-week intervention window.", created_at: "2026-01-08T09:01:06Z", metadata: { reporting_week: "2026-W02", confidence: 0.74 }, timeline: [{ event: "CEO_RECOMMEND", detail: "Pre-Churn Signal: 3 accounts set cancel_at_period_end — outreach immediately." }] },
    ],
    attributionEntries: [],
  },

  /* ── 5. THE FLAT LINE ──────────────────────────────────────────────────────── */
  {
    id: "flat_line",
    label: "The Flat Line",
    description: "Stable mature SaaS — zero triggers, zero escalations, control scenario",
    badge: "stable",
    data: {
      reporting_week: "2026-W08",
      last_run: "2026-02-19T09:00:00Z",
      mrr: { current: 50400, previous: 50200, change_pct: 0.40 },
      active_subscriptions: 204,
      churn: { rate: 0.0, at_risk: 0, reason: "Stable growth continuing — no action required. Normal churn/expansion balance maintained." },
      velocity: { opened: 22, closed: 22, net: 0, avg_close_hrs: 27.5, backlog: 80 },
      blocked: [],
      confidence: { current: 0.82, history: [0.80, 0.81, 0.79, 0.82, 0.80, 0.81, 0.80, 0.82] },
      red_flags: [],
      skills: [
        { name: "saas_metrics_dashboard", tier: 0, agent: "CFO", status: "healthy", success_rate: 100 },
        { name: "unit_economics_rule40", tier: 0, agent: "CFO", status: "healthy", success_rate: 100 },
        { name: "github_issue_auto_triage", tier: 1, agent: "PM", status: "healthy", success_rate: 98 },
        { name: "weekly_digest_delivery", tier: 1, agent: "CEO", status: "healthy", success_rate: 100 },
        { name: "dogfood_audit_cycle", tier: 0, agent: "system", status: "healthy", success_rate: 100 },
      ],
      digests: [
        { period: "2026-W08", status: "delivered", channel: "slack" },
        { period: "2026-W07", status: "delivered", channel: "email" },
        { period: "2026-W06", status: "delivered", channel: "slack" },
      ],
      cost: { last_run: 0.00034, monthly: 0.014, ceiling: 25.0 },
      recommendation: "Business stable and healthy. MRR growing +0.4% WoW within normal range. No playbooks triggered, no escalations warranted. Engineering velocity balanced (22/22). Continue current trajectory — no action required this week.",
      advisor_note: "8 consecutive weeks without playbook trigger or escalation — system correctly identifying stable state. False positive rate: 0%. Confidence stable at 0.80-0.82 range indicates well-calibrated model. This is the benchmark control scenario.",
      advisor_confidence: 0.82,
      playbook_match: { name: "None (stable)", success_rate: 1.0, applications: 0, flag: "none" },
      unit_economics: { rule40_score: 38.4, health_grade: "Strong", ltv_simple: 12600, arpu: 247.1, quick_ratio: 2.8, nrr_pct: 101.2 },
      triage: { total: 22, categories: { bug: 3, feature: 8, chore: 7, question: 4 }, priorities: { P0: 0, P1: 0, P2: 8, P3: 14 }, pending_review: 2 },
      audit_events: [
        { event_type: "RUN_COMPLETE", severity: "info", message: "Weekly run W08 completed. MRR: $50,400 (+0.4%). No flags.", created_at: "2026-02-19T09:01:12Z" },
        { event_type: "CONFIDENCE_RECORDED", severity: "info", message: "CEO confidence: 0.82 — stable, 8-week healthy baseline.", created_at: "2026-02-19T09:01:08Z" },
        { event_type: "SLACK_SENT", severity: "info", message: "W08 digest posted to #all-ai-ops-dogfood.", created_at: "2026-02-19T09:01:06Z" },
      ],
      deltas: { mrr_pct: 0.40, velocity_net: 0, backlog_delta: -1, confidence_delta: 0.02 },
      saved_mrr: { direct: { amount: 0, actions: 0, avg_confidence: null }, likely: { amount: 0, actions: 0, avg_confidence: null }, reported: { amount: 0, actions: 0, avg_confidence: null } },
      memory_health: { total_pages: 8, matches_found: 0, avg_relevance: 0.0, active_playbooks: 0, stale_playbooks: 0 },
      llm_provider: "Gemini 2.5 Flash",
      cross_model_consistency: 96,
    },
    memoryPages: [
      { id: "fl-w08", title: "2026-W08 Operational Report", category: "reporting", tags: [], compiled_truth: "MRR rose 0.4% to $50,400. 204 subs. Stable. 22 issues opened and closed. 0 flags. Confidence: 0.82.", created_at: "2026-02-19T09:01:06Z", metadata: { reporting_week: "2026-W08", confidence: 0.82 }, timeline: [{ event: "RUN_COMPLETE", detail: "Stable week — no flags." }] },
      { id: "fl-w06", title: "2026-W06 Operational Report", category: "reporting", tags: [], compiled_truth: "MRR rose 0.4% to $50,300. 203 subs. Stable. No flags. Confidence: 0.81.", created_at: "2026-02-05T09:01:06Z", metadata: { reporting_week: "2026-W06", confidence: 0.81 }, timeline: [{ event: "RUN_COMPLETE", detail: "Stable week — no flags." }] },
      { id: "fl-w04", title: "2026-W04 Operational Report", category: "reporting", tags: [], compiled_truth: "MRR rose 0.6% to $50,200. 202 subs. Stable. No flags. Confidence: 0.82.", created_at: "2026-01-22T09:01:06Z", metadata: { reporting_week: "2026-W04", confidence: 0.82 }, timeline: [{ event: "RUN_COMPLETE", detail: "Stable week — no flags." }] },
    ],
    attributionEntries: [],
  },

  /* ── 6. THE ONBOARDING BLACK HOLE ─────────────────────────────────────────── */
  {
    id: "onboarding_blackhole",
    label: "The Onboarding Black Hole",
    description: "New cohort never activates — churn from low feature adoption",
    badge: "churn",
    data: {
      reporting_week: "2026-W04",
      last_run: "2026-01-22T09:00:00Z",
      mrr: { current: 7900, previous: 8500, change_pct: -7.06 },
      active_subscriptions: 89,
      churn: { rate: 0.07, at_risk: 6, reason: "Onboarding cohort churning due to activation failure — 7 lost this week. Core feature adoption at 22%. 24 support tickets unresolved." },
      velocity: { opened: 22, closed: 13, net: 9, avg_close_hrs: 45.0, backlog: 59 },
      blocked: [],
      confidence: { current: 0.62, history: [0.78, 0.74, 0.68, 0.62] },
      red_flags: [
        { metric: "Onboarding Failure", severity: "critical", detail: "Core feature adoption: 22% (baseline 72%). 7 churns this week from W2 onboarding cohort." },
        { metric: "Support Overload", severity: "warning", detail: "24 support tickets open — 3× normal volume. Onboarding confusion driving ticket surge." },
      ],
      skills: [
        { name: "saas_metrics_dashboard", tier: 0, agent: "CFO", status: "healthy", success_rate: 100 },
        { name: "onboarding_health_check", tier: 1, agent: "PM", status: "failing", success_rate: 58 },
        { name: "pre_churn_signal", tier: 1, agent: "CEO", status: "healthy", success_rate: 82 },
        { name: "github_issue_auto_triage", tier: 1, agent: "PM", status: "healthy", success_rate: 91 },
      ],
      digests: [
        { period: "2026-W04", status: "delivered", channel: "slack" },
        { period: "2026-W03", status: "delivered", channel: "email" },
      ],
      cost: { last_run: 0.00039, monthly: 0.016, ceiling: 25.0 },
      recommendation: "ESCALATION: Onboarding failure + MRR cliff (2 signals). 7 churns from W2 cohort — all had <30% feature adoption. Deploy new onboarding flow immediately. Assign customer success to the 6 remaining at-risk accounts. Add activation checkpoint at day 7: accounts below 40% feature adoption should trigger automatic CSM outreach.",
      advisor_note: "Advisor flagged onboarding failure at W3 before churn hit at W4 — 1-week lead time. Pattern: new-cohort activation below 40% → churn rate 60-70% at 30-day mark. Matches prior playbook run. Revised onboarding flow reduced churn by 58% in previous activation.",
      advisor_confidence: 0.62,
      playbook_match: { name: "Onboarding Health Check", success_rate: 0.65, applications: 2, flag: "moderate" },
      unit_economics: { rule40_score: -14.1, health_grade: "Critical", ltv_simple: 1185, arpu: 88.8, quick_ratio: 0.5, nrr_pct: 85.6 },
      triage: { total: 22, categories: { bug: 6, feature: 5, chore: 4, question: 7 }, priorities: { P0: 1, P1: 5, P2: 10, P3: 6 }, pending_review: 5 },
      audit_events: [
        { event_type: "RISK_ESCALATION", severity: "critical", message: "W04 escalation: onboarding failure + MRR cliff (2 independent signals).", created_at: "2026-01-22T09:01:12Z" },
        { event_type: "RED_FLAG_RAISED", severity: "critical", message: "7 churns from W2 onboarding cohort — activation rate 22%.", created_at: "2026-01-22T09:01:11Z" },
        { event_type: "ADVISOR_MATCH", severity: "warning", message: "Onboarding Health Check: pre-churn signal confirmed from W3 advisory.", created_at: "2026-01-22T09:01:09Z" },
        { event_type: "MEMORY_WRITTEN", severity: "info", message: "Memory page: 2026-W04 Onboarding Failure (4 chunks).", created_at: "2026-01-22T09:01:06Z" },
      ],
      deltas: { mrr_pct: -7.06, velocity_net: 9, backlog_delta: 9, confidence_delta: -0.06 },
      saved_mrr: { direct: { amount: 0, actions: 0, avg_confidence: null }, likely: { amount: 0, actions: 0, avg_confidence: null }, reported: { amount: 0, actions: 0, avg_confidence: null } },
      memory_health: { total_pages: 4, matches_found: 2, avg_relevance: 0.79, active_playbooks: 2, stale_playbooks: 0 },
      llm_provider: "Gemini 2.5 Flash",
      cross_model_consistency: 84,
    },
    memoryPages: [
      { id: "ob-w04", title: "2026-W04 Onboarding Failure Escalation", category: "churn_prevention", tags: ["churn", "mrr-decline", "red-flags"], compiled_truth: "MRR declined 7.06% to $7,900. 89 subs. 7 churns from W2 cohort — activation 22%. ESCALATION. 24 support tickets. Confidence: 0.62.", created_at: "2026-01-22T09:01:06Z", metadata: { reporting_week: "2026-W04", confidence: 0.62 }, timeline: [{ event: "RISK_ESCALATION", detail: "Onboarding failure confirmed — 7 churns from low-activation cohort." }] },
      { id: "ob-w03", title: "2026-W03 Onboarding Risk Alert", category: "churn_prevention", tags: ["churn"], compiled_truth: "MRR rose 1.2% to $8,500. 94 subs. New cohort at 28% adoption — onboarding failure in progress. Advisor flagged pre-churn signal.", created_at: "2026-01-15T09:01:06Z", metadata: { reporting_week: "2026-W03", confidence: 0.68 }, timeline: [{ event: "CEO_RECOMMEND", detail: "Pre-churn signal: 4 accounts at <30% activation — intervene now." }] },
      { id: "ob-w02", title: "2026-W02 Onboarding Health Check", category: "churn_prevention", tags: ["churn"], compiled_truth: "MRR rose 5.0% to $8,400. 90 subs. New 10-account cohort at 45% adoption — below 70% threshold. Onboarding Health Check triggered.", created_at: "2026-01-08T09:01:06Z", metadata: { reporting_week: "2026-W02", confidence: 0.74 }, timeline: [{ event: "CEO_RECOMMEND", detail: "Onboarding Health Check: new cohort below activation threshold." }] },
    ],
    attributionEntries: [],
  },

  /* ── 7. THE PRICING SHOCKWAVE ──────────────────────────────────────────────── */
  {
    id: "pricing_shockwave",
    label: "The Pricing Shockwave",
    description: "Price increase triggers downgrade wave — ARPU erosion, grandfathering",
    badge: "churn",
    data: {
      reporting_week: "2026-W04",
      last_run: "2026-01-22T09:00:00Z",
      mrr: { current: 16900, previous: 17600, change_pct: -3.98 },
      active_subscriptions: 119,
      churn: { rate: 0.02, at_risk: 12, reason: "Pricing contraction deepening: 12 downgrades + 2 churns. ARPU declining from $150 to $142. Grandfathering programme not yet deployed." },
      velocity: { opened: 15, closed: 12, net: 3, avg_close_hrs: 40.0, backlog: 47 },
      blocked: [],
      confidence: { current: 0.64, history: [0.79, 0.76, 0.70, 0.64] },
      red_flags: [
        { metric: "ARPU Erosion", severity: "critical", detail: "ARPU dropped from $150 to $142 in 4 weeks. 12 downgrades this week alone." },
        { metric: "Pricing Contraction", severity: "critical", detail: "Price increase → 14 downgrades + 2 churns in 2 weeks. MRR cliff risk." },
      ],
      skills: [
        { name: "saas_metrics_dashboard", tier: 0, agent: "CFO", status: "healthy", success_rate: 100 },
        { name: "pre_churn_signal", tier: 1, agent: "CEO", status: "healthy", success_rate: 74 },
        { name: "pricing_contraction_alert", tier: 1, agent: "CFO", status: "healthy", success_rate: 81 },
        { name: "github_issue_auto_triage", tier: 1, agent: "PM", status: "healthy", success_rate: 96 },
      ],
      digests: [
        { period: "2026-W04", status: "delivered", channel: "slack" },
        { period: "2026-W03", status: "delivered", channel: "email" },
      ],
      cost: { last_run: 0.00037, monthly: 0.016, ceiling: 25.0 },
      recommendation: "ESCALATION: Pricing contraction + ARPU erosion (2 signals). Deploy grandfathering programme immediately: lock current pricing for existing customers for 90 days. Focus new pricing only on new customers. 12 at-risk accounts need personal outreach citing loyalty discount. Each downgrade = -$8/mo average; recovery window closing.",
      advisor_note: "Pricing sensitivity pattern confirmed — W2 announcement → W3-4 contraction mirrors prior-year pricing change. Grandfathering reduces contraction by ~60% in comparable scenarios. Deploy before W5 or risk second downgrade wave from remaining at-risk accounts.",
      advisor_confidence: 0.64,
      playbook_match: { name: "Pre-Churn Signal", success_rate: 0.74, applications: 2, flag: "moderate" },
      unit_economics: { rule40_score: -6.0, health_grade: "Critical", ltv_simple: 3380, arpu: 142.0, quick_ratio: 0.7, nrr_pct: 88.9 },
      triage: { total: 15, categories: { bug: 2, feature: 6, chore: 5, question: 2 }, priorities: { P0: 0, P1: 2, P2: 7, P3: 6 }, pending_review: 2 },
      audit_events: [
        { event_type: "RISK_ESCALATION", severity: "critical", message: "W04 escalation: pricing contraction + ARPU erosion (2 independent signals).", created_at: "2026-01-22T09:01:12Z" },
        { event_type: "RED_FLAG_RAISED", severity: "critical", message: "ARPU declined $150→$142. 12 downgrades this week.", created_at: "2026-01-22T09:01:11Z" },
        { event_type: "ADVISOR_MATCH", severity: "warning", message: "Pre-Churn Signal: pricing-triggered contraction mirrors prior-year pattern.", created_at: "2026-01-22T09:01:09Z" },
        { event_type: "MEMORY_WRITTEN", severity: "info", message: "Memory page: 2026-W04 Pricing Shockwave Escalation (3 chunks).", created_at: "2026-01-22T09:01:06Z" },
      ],
      deltas: { mrr_pct: -3.98, velocity_net: 3, backlog_delta: 3, confidence_delta: -0.06 },
      saved_mrr: { direct: { amount: 0, actions: 0, avg_confidence: null }, likely: { amount: 0, actions: 0, avg_confidence: null }, reported: { amount: 0, actions: 0, avg_confidence: null } },
      memory_health: { total_pages: 4, matches_found: 2, avg_relevance: 0.82, active_playbooks: 1, stale_playbooks: 0 },
      llm_provider: "Gemini 2.5 Flash",
      cross_model_consistency: 85,
    },
    memoryPages: [
      { id: "ps-w04", title: "2026-W04 Pricing Shockwave Escalation", category: "churn_prevention", tags: ["mrr-decline", "churn", "red-flags"], compiled_truth: "MRR declined 3.98% to $16,900. 119 subs. 12 downgrades + 2 churns post-price increase. ARPU: $142 (down from $150). ESCALATION.", created_at: "2026-01-22T09:01:06Z", metadata: { reporting_week: "2026-W04", confidence: 0.64 }, timeline: [{ event: "RISK_ESCALATION", detail: "Pricing contraction + ARPU erosion — grandfathering required." }] },
      { id: "ps-w03", title: "2026-W03 Pricing Contraction Begins", category: "churn_prevention", tags: ["mrr-decline", "churn"], compiled_truth: "MRR declined 3.30% to $17,600. 121 subs. 8 downgrades following price announcement. ARPU: $145.5. Pre-Churn Signal triggered.", created_at: "2026-01-15T09:01:06Z", metadata: { reporting_week: "2026-W03", confidence: 0.70 }, timeline: [{ event: "CEO_RECOMMEND", detail: "Pre-Churn Signal: pricing-triggered contraction — intervene before W4." }] },
      { id: "ps-w02", title: "2026-W02 Price Increase Announced", category: "retention", tags: ["churn"], compiled_truth: "MRR rose 1.1% to $18,200. 122 subs. Pricing increase announced — 5 accounts expressing concern. No revenue impact yet.", created_at: "2026-01-08T09:01:06Z", metadata: { reporting_week: "2026-W02", confidence: 0.76 }, timeline: [{ event: "CEO_RECOMMEND", detail: "Pricing announcement — monitor downgrade signals W3." }] },
    ],
    attributionEntries: [],
  },

  /* ── 8. THE NOISY DATA WEEK ────────────────────────────────────────────────── */
  {
    id: "noisy_data",
    label: "The Noisy Data Week",
    description: "Duplicate runs, partial sync, missed week — system abstains correctly",
    badge: "data",
    data: {
      reporting_week: "2026-W04",
      last_run: "2026-01-22T09:00:00Z",
      mrr: { current: 15000, previous: 30200, change_pct: -50.33 },
      active_subscriptions: 70,
      churn: { rate: 0.0, at_risk: 0, reason: "⚠ PARTIAL SYNC DETECTED — data incomplete. MRR figures are unreliable. Actual MRR ~$30,200. Do not act on this week's metrics." },
      velocity: { opened: 10, closed: 0, net: 10, avg_close_hrs: 0.0, backlog: 30 },
      blocked: [],
      confidence: { current: 0.38, history: [0.79, 0.81, 0.79, 0.38] },
      red_flags: [
        { metric: "DATA QUALITY", severity: "critical", detail: "Partial sync detected — W04 data shows only 50% of accounts. MRR and velocity figures unreliable. Previous clean data: W02 ($30,200 MRR, 142 subs)." },
      ],
      skills: [
        { name: "saas_metrics_dashboard", tier: 0, agent: "CFO", status: "stale", success_rate: 42 },
        { name: "data_quality_guard", tier: 0, agent: "system", status: "healthy", success_rate: 100 },
        { name: "github_issue_auto_triage", tier: 1, agent: "PM", status: "stale", success_rate: 55 },
        { name: "weekly_digest_delivery", tier: 1, agent: "CEO", status: "healthy", success_rate: 100 },
      ],
      digests: [
        { period: "2026-W04", status: "delivered", channel: "slack" },
        { period: "2026-W03", status: "delivered", channel: "email" },
      ],
      cost: { last_run: 0.00029, monthly: 0.012, ceiling: 25.0 },
      recommendation: "⚠ DATA QUALITY FLAG: Partial sync detected on W04. MRR showing $15,000 (50% of expected $30,200) — data pipeline incomplete. Recommending NO operational decisions based on W04 metrics. Re-run data sync and reprocess W04 before acting. W03 data (duplicate run) also flagged as non-authoritative.",
      advisor_note: "System correctly abstaining on bad data — W03 duplicate_run + W04 partial_sync = zero confidence in trend analysis. Prior precedent: W01-W02 were clean ($30,000-$30,200). Backfill required before confidence can recover. No false escalations triggered.",
      advisor_confidence: 0.38,
      playbook_match: { name: "Data Quality Guard", success_rate: 1.0, applications: 1, flag: "abstain" },
      unit_economics: { rule40_score: 12.1, health_grade: "Adequate", ltv_simple: 7550, arpu: 214.3, quick_ratio: 1.8, nrr_pct: 99.8 },
      triage: { total: 10, categories: { bug: 3, feature: 2, chore: 3, question: 2 }, priorities: { P0: 0, P1: 1, P2: 4, P3: 5 }, pending_review: 1 },
      audit_events: [
        { event_type: "DATA_QUALITY_FLAG", severity: "warning", message: "W04 partial_sync: only 70/142 accounts synced. MRR unreliable.", created_at: "2026-01-22T09:01:12Z" },
        { event_type: "DATA_QUALITY_FLAG", severity: "warning", message: "W03 duplicate_run: identical data to W02. No new signals extracted.", created_at: "2026-01-22T09:01:11Z" },
        { event_type: "CONFIDENCE_RECORDED", severity: "warning", message: "CEO confidence dropped to 0.38 — data quality insufficient for recommendations.", created_at: "2026-01-22T09:01:09Z" },
        { event_type: "MEMORY_WRITTEN", severity: "info", message: "Memory page: 2026-W04 Data Quality Incident (2 chunks, low confidence).", created_at: "2026-01-22T09:01:06Z" },
      ],
      deltas: { mrr_pct: -50.33, velocity_net: 10, backlog_delta: -31, confidence_delta: -0.41 },
      saved_mrr: { direct: { amount: 0, actions: 0, avg_confidence: null }, likely: { amount: 0, actions: 0, avg_confidence: null }, reported: { amount: 0, actions: 0, avg_confidence: null } },
      memory_health: { total_pages: 4, matches_found: 0, avg_relevance: 0.0, active_playbooks: 0, stale_playbooks: 1 },
      llm_provider: "Gemini 2.5 Flash",
      cross_model_consistency: 71,
    },
    memoryPages: [
      { id: "nd-w04", title: "2026-W04 Partial Sync Incident", category: "reporting", tags: ["red-flags"], compiled_truth: "PARTIAL SYNC: W04 data shows only 50% of accounts synced. MRR $15,000 (unreliable). GitHub: 0 issues closed. Confidence: 0.38. No operational decisions should use W04 data.", created_at: "2026-01-22T09:01:06Z", metadata: { reporting_week: "2026-W04", confidence: 0.38 }, timeline: [{ event: "DATA_QUALITY_FLAG", detail: "Partial sync — 70/142 accounts. Data pipeline incomplete." }] },
      { id: "nd-w03", title: "2026-W03 Duplicate Run Flagged", category: "reporting", tags: [], compiled_truth: "DUPLICATE RUN: W03 data identical to W02. No new signals. MRR $30,200 (same as W02). System flagged and did not update memory.", created_at: "2026-01-15T09:01:06Z", metadata: { reporting_week: "2026-W03", confidence: 0.79 }, timeline: [{ event: "DATA_QUALITY_FLAG", detail: "Duplicate run — data matches W02 exactly. No memory contamination." }] },
      { id: "nd-w02", title: "2026-W02 Operational Report", category: "reporting", tags: [], compiled_truth: "MRR rose 0.67% to $30,200. 142 subs. Clean data. Last known-good baseline.", created_at: "2026-01-08T09:01:06Z", metadata: { reporting_week: "2026-W02", confidence: 0.81 }, timeline: [{ event: "RUN_COMPLETE", detail: "Clean data — last known-good baseline before data quality incidents." }] },
    ],
    attributionEntries: [],
  },

  /* ── 9. THE ACQUISITION SPIKE ──────────────────────────────────────────────── */
  {
    id: "acquisition_spike",
    label: "The Acquisition Spike",
    description: "Single enterprise account distorts all metrics — 43% MRR concentration risk",
    badge: "risk",
    data: {
      reporting_week: "2026-W07",
      last_run: "2026-02-12T09:00:00Z",
      mrr: { current: 11200, previous: 19000, change_pct: -41.05 },
      active_subscriptions: 75,
      churn: { rate: 0.01, at_risk: 0, reason: "Meridian Corp cancelled ($8,000 MRR lost) — MRR reverts near W1 baseline. 41% contraction from single account exit." },
      velocity: { opened: 15, closed: 12, net: 3, avg_close_hrs: 35.0, backlog: 54 },
      blocked: [
        { id: "GH-201", title: "Enterprise SSO integration — post-cancellation cleanup", since: "2026-03-10", reason: "Meridian Corp-specific feature needs deprecation plan" },
      ],
      confidence: { current: 0.61, history: [0.80, 0.78, 0.77, 0.73, 0.71, 0.70, 0.61] },
      red_flags: [
        { metric: "Concentration Risk Executed", severity: "critical", detail: "Meridian Corp cancelled — $8,000 MRR (43% of peak) gone. MRR reverts to $11,200." },
        { metric: "Pipeline Dependency", severity: "critical", detail: "Engineering capacity tied to ex-customer feature (GH-201). Opportunity cost: 3 weeks." },
      ],
      skills: [
        { name: "saas_metrics_dashboard", tier: 0, agent: "CFO", status: "healthy", success_rate: 100 },
        { name: "concentration_risk_alert", tier: 1, agent: "CEO", status: "healthy", success_rate: 84 },
        { name: "github_issue_auto_triage", tier: 1, agent: "PM", status: "healthy", success_rate: 95 },
        { name: "weekly_digest_delivery", tier: 1, agent: "CEO", status: "healthy", success_rate: 100 },
      ],
      digests: [
        { period: "2026-W07", status: "delivered", channel: "slack" },
        { period: "2026-W06", status: "delivered", channel: "email" },
      ],
      cost: { last_run: 0.00038, monthly: 0.016, ceiling: 25.0 },
      recommendation: "ESCALATION: Meridian Corp cancelled — 41% MRR contraction. As warned at W2 (Concentration Risk Alert), single-account dependency was the key risk. Immediate actions: (1) deprecate GH-201 enterprise SSO feature, (2) launch pipeline diversification — no single account above 10% MRR target, (3) activate 3 enterprise prospects from waiting list.",
      advisor_note: "Concentration risk materialised exactly as flagged at W2. W4 escalation (champion departure) was the last intervention point. W2-4 pattern confirms: enterprise pilots without multi-stakeholder anchoring have 70% 6-month churn rate. Recommend: min. 3 stakeholders for any account >15% MRR.",
      advisor_confidence: 0.61,
      playbook_match: { name: "Concentration Risk Alert", success_rate: 0.84, applications: 5, flag: "strong" },
      unit_economics: { rule40_score: 6.8, health_grade: "Adequate", ltv_simple: 1680, arpu: 149.3, quick_ratio: 1.4, nrr_pct: 78.3 },
      triage: { total: 15, categories: { bug: 4, feature: 4, chore: 5, question: 2 }, priorities: { P0: 1, P1: 3, P2: 6, P3: 5 }, pending_review: 3 },
      audit_events: [
        { event_type: "RISK_ESCALATION", severity: "critical", message: "W07 escalation: Meridian Corp cancellation — 41% MRR drop from single account.", created_at: "2026-02-12T09:01:12Z" },
        { event_type: "RED_FLAG_RAISED", severity: "critical", message: "Concentration risk executed: $8,000 MRR lost. Predicted at W2, W4.", created_at: "2026-02-12T09:01:11Z" },
        { event_type: "ADVISOR_MATCH", severity: "warning", message: "Concentration Risk Alert: W2-W4 precedent confirmed. Pipeline diversification required.", created_at: "2026-02-12T09:01:09Z" },
        { event_type: "MEMORY_WRITTEN", severity: "info", message: "Memory page: 2026-W07 Acquisition Spike Resolution (4 chunks).", created_at: "2026-02-12T09:01:06Z" },
      ],
      deltas: { mrr_pct: -41.05, velocity_net: 3, backlog_delta: 3, confidence_delta: -0.09 },
      saved_mrr: { direct: { amount: 0, actions: 0, avg_confidence: null }, likely: { amount: 0, actions: 0, avg_confidence: null }, reported: { amount: 0, actions: 0, avg_confidence: null } },
      memory_health: { total_pages: 7, matches_found: 4, avg_relevance: 0.86, active_playbooks: 1, stale_playbooks: 0 },
      llm_provider: "Gemini 2.5 Flash",
      cross_model_consistency: 87,
    },
    memoryPages: [
      { id: "as-w07", title: "2026-W07 Concentration Risk Executed", category: "churn_prevention", tags: ["mrr-decline", "red-flags", "churn"], compiled_truth: "MRR dropped 41% to $11,200. Meridian Corp cancelled ($8,000 MRR). MRR reverts to W1 baseline. ESCALATION. Pipeline diversification required.", created_at: "2026-02-12T09:01:06Z", metadata: { reporting_week: "2026-W07", confidence: 0.61 }, timeline: [{ event: "RISK_ESCALATION", detail: "Meridian Corp cancellation executed — concentration risk materialised." }] },
      { id: "as-w04", title: "2026-W04 Champion Departure Escalation", category: "churn_prevention", tags: ["churn", "red-flags"], compiled_truth: "MRR $18,800. Meridian Corp champion left company — 43% MRR concentration risk escalated. ESCALATION. Outreach to new stakeholder initiated.", created_at: "2026-01-22T09:01:06Z", metadata: { reporting_week: "2026-W04", confidence: 0.73 }, timeline: [{ event: "RISK_ESCALATION", detail: "Champion departure — last intervention window before cancellation." }] },
      { id: "as-w02", title: "2026-W02 Concentration Risk Alert", category: "retention", tags: ["churn"], compiled_truth: "MRR spiked 85.7% to $18,200. Meridian Corp signed ($8,000 MRR). ARPU distorted to $275. Concentration Risk Alert: single account = 44% of MRR. System correctly did not declare organic growth.", created_at: "2026-01-08T09:01:06Z", metadata: { reporting_week: "2026-W02", confidence: 0.78 }, timeline: [{ event: "CEO_RECOMMEND", detail: "Concentration Risk Alert — spike is single-customer, not organic." }] },
    ],
    attributionEntries: [],
  },

  /* ── 10. THE REFUND WAVE ────────────────────────────────────────────────────── */
  {
    id: "refund_wave",
    label: "The Refund Wave",
    description: "Billing bug causes mass refunds — support overload, churn from trust damage",
    badge: "churn",
    data: {
      reporting_week: "2026-W03",
      last_run: "2026-01-15T09:00:00Z",
      mrr: { current: 19800, previous: 21200, change_pct: -6.60 },
      active_subscriptions: 110,
      churn: { rate: 0.03, at_risk: 8, reason: "Refund wave escalating — 3 accounts cancelled post-refund. 8 more expressing intent to cancel. Support queue at 72h SLA breach. Root cause: billing webhook double-charge." },
      velocity: { opened: 28, closed: 10, net: 18, avg_close_hrs: 72.0, backlog: 80 },
      blocked: [
        { id: "GH-401", title: "Billing webhook double-charge on plan upgrade", since: "2026-02-03", reason: "Payment processor retry logic sending duplicate charges" },
        { id: "GH-412", title: "Support queue overflow — refund processing SLA breach", since: "2026-02-10", reason: "Support team at capacity; automated refund tool not deployed" },
      ],
      confidence: { current: 0.58, history: [0.82, 0.74, 0.58] },
      red_flags: [
        { metric: "Billing Bug", severity: "critical", detail: "18 accounts double-billed. Refund wave: $1,400 MRR lost via Stripe credits this week." },
        { metric: "Support SLA Breach", severity: "critical", detail: "67 support tickets open (8× normal). SLA at 72h — accounts escalating to social media." },
      ],
      skills: [
        { name: "saas_metrics_dashboard", tier: 0, agent: "CFO", status: "healthy", success_rate: 100 },
        { name: "refund_escalation", tier: 1, agent: "CEO", status: "healthy", success_rate: 78 },
        { name: "github_issue_auto_triage", tier: 1, agent: "PM", status: "failing", success_rate: 51 },
        { name: "weekly_digest_delivery", tier: 1, agent: "CEO", status: "healthy", success_rate: 100 },
      ],
      digests: [
        { period: "2026-W03", status: "delivered", channel: "slack" },
        { period: "2026-W02", status: "delivered", channel: "email" },
      ],
      cost: { last_run: 0.00042, monthly: 0.018, ceiling: 25.0 },
      recommendation: "ESCALATION: Refund wave + support overload (2 signals). Fix GH-401 (billing webhook) today — every hour of delay adds more double-charge victims. Deploy automated refund tool (GH-412) to clear support queue. Personal apology + credit to all 18 affected accounts. This is a trust crisis, not just a billing bug.",
      advisor_note: "Refund-driven MRR drop is distinct from churn-driven drop — subscribers still active but Stripe credits reduce net MRR. Trust damage is the secondary risk. Historical data: billing incidents resolved within 72h have 85% customer retention. Beyond 72h: 40% retention. Clock started W02.",
      advisor_confidence: 0.58,
      playbook_match: { name: "Refund Escalation", success_rate: 0.78, applications: 1, flag: "strong" },
      unit_economics: { rule40_score: -18.6, health_grade: "Critical", ltv_simple: 4950, arpu: 180.0, quick_ratio: 0.4, nrr_pct: 84.2 },
      triage: { total: 28, categories: { bug: 20, feature: 2, chore: 4, question: 2 }, priorities: { P0: 2, P1: 10, P2: 12, P3: 4 }, pending_review: 8 },
      audit_events: [
        { event_type: "RISK_ESCALATION", severity: "critical", message: "W03 escalation: refund surge + support overload (2 independent signals).", created_at: "2026-01-15T09:01:12Z" },
        { event_type: "RED_FLAG_RAISED", severity: "critical", message: "67 support tickets — 8× normal. SLA breach. 3 accounts cancelled post-refund.", created_at: "2026-01-15T09:01:11Z" },
        { event_type: "ADVISOR_MATCH", severity: "warning", message: "Refund Escalation playbook: trust damage risk — resolve within 72h.", created_at: "2026-01-15T09:01:09Z" },
        { event_type: "MEMORY_WRITTEN", severity: "info", message: "Memory page: 2026-W03 Refund Wave Escalation (4 chunks).", created_at: "2026-01-15T09:01:06Z" },
      ],
      deltas: { mrr_pct: -6.60, velocity_net: 18, backlog_delta: 18, confidence_delta: -0.16 },
      saved_mrr: { direct: { amount: 0, actions: 0, avg_confidence: null }, likely: { amount: 0, actions: 0, avg_confidence: null }, reported: { amount: 0, actions: 0, avg_confidence: null } },
      memory_health: { total_pages: 3, matches_found: 1, avg_relevance: 0.78, active_playbooks: 1, stale_playbooks: 0 },
      llm_provider: "Gemini 2.5 Flash",
      cross_model_consistency: 82,
    },
    memoryPages: [
      { id: "rw-w03", title: "2026-W03 Refund Wave Escalation", category: "churn_prevention", tags: ["mrr-decline", "red-flags", "bug-spike"], compiled_truth: "MRR declined 6.6% to $19,800. 110 subs. 67 support tickets. 3 cancellations post-refund. ESCALATION. Billing webhook bug: 18 accounts double-charged.", created_at: "2026-01-15T09:01:06Z", metadata: { reporting_week: "2026-W03", confidence: 0.58 }, timeline: [{ event: "RISK_ESCALATION", detail: "Refund wave + support overload — 2 independent signals." }] },
      { id: "rw-w02", title: "2026-W02 Billing Bug Detected", category: "churn_prevention", tags: ["mrr-decline", "bug-spike"], compiled_truth: "MRR declined 3.6% to $21,200. Billing webhook double-charge: 18 accounts affected. 34 support tickets. Refund Escalation playbook triggered.", created_at: "2026-01-08T09:01:06Z", metadata: { reporting_week: "2026-W02", confidence: 0.74 }, timeline: [{ event: "CEO_RECOMMEND", detail: "Billing bug detected — mass refund requests incoming." }] },
    ],
    attributionEntries: [],
  },

  /* ── 11. THE COMPETITOR LAUNCH ─────────────────────────────────────────────── */
  {
    id: "competitor_launch",
    label: "The Competitor Launch",
    description: "Competitive displacement — feature gap churn, engineering response",
    badge: "churn",
    data: {
      reporting_week: "2026-W04",
      last_run: "2026-01-22T09:00:00Z",
      mrr: { current: 33800, previous: 35200, change_pct: -3.98 },
      active_subscriptions: 174,
      churn: { rate: 0.03, at_risk: 12, reason: "Competitive churn accelerating — 6 churns in one week. 80% of exit surveys mention DataPulse AI. 12 accounts actively evaluating competitor." },
      velocity: { opened: 42, closed: 14, net: 28, avg_close_hrs: 58.0, backlog: 116 },
      blocked: [
        { id: "GH-501", title: "AI-assisted anomaly detection — competitive feature request", since: "2026-02-17", reason: "Deprioritised last quarter — now critical for retention" },
        { id: "GH-518", title: "Natural language query interface", since: "2026-02-24", reason: "Requires ML infrastructure not yet in place" },
      ],
      confidence: { current: 0.59, history: [0.80, 0.78, 0.72, 0.59] },
      red_flags: [
        { metric: "Competitive Displacement", severity: "critical", detail: "DataPulse AI shipped major AI feature. 80% of churned accounts cite competitor in exit surveys." },
        { metric: "Feature Gap Crisis", severity: "critical", detail: "42 issues opened this week — 60% competitive feature requests. Backlog at 116." },
      ],
      skills: [
        { name: "saas_metrics_dashboard", tier: 0, agent: "CFO", status: "healthy", success_rate: 100 },
        { name: "competitive_displacement_alert", tier: 1, agent: "CEO", status: "healthy", success_rate: 80 },
        { name: "github_issue_auto_triage", tier: 1, agent: "PM", status: "failing", success_rate: 64 },
        { name: "weekly_digest_delivery", tier: 1, agent: "CEO", status: "healthy", success_rate: 100 },
      ],
      digests: [
        { period: "2026-W04", status: "delivered", channel: "slack" },
        { period: "2026-W03", status: "delivered", channel: "email" },
      ],
      cost: { last_run: 0.00043, monthly: 0.018, ceiling: 25.0 },
      recommendation: "ESCALATION: Competitive churn acceleration + feature gap crisis (2 signals). Ship GH-501 (AI anomaly detection) within 2 weeks — 11 accounts waiting on this feature. Hold accounts evaluating competitor with 90-day feature roadmap commitment. Engineering sprint required: competitive parity is a survival issue.",
      advisor_note: "Competitive displacement pattern: feature announcement → evaluation period → churn wave (3-5 week lag). Currently at week 1 of churn wave. Historical parallel: 2023 competitor launch caused 18% MRR loss over 8 weeks. Engineering response within 3 weeks reduced that to 9%. Act now.",
      advisor_confidence: 0.59,
      playbook_match: { name: "Competitive Displacement Alert", success_rate: 0.80, applications: 1, flag: "strong" },
      unit_economics: { rule40_score: -10.0, health_grade: "Critical", ltv_simple: 6760, arpu: 194.3, quick_ratio: 0.6, nrr_pct: 88.6 },
      triage: { total: 42, categories: { bug: 6, feature: 28, chore: 5, question: 3 }, priorities: { P0: 1, P1: 12, P2: 20, P3: 9 }, pending_review: 10 },
      audit_events: [
        { event_type: "RISK_ESCALATION", severity: "critical", message: "W04 escalation: competitive churn + feature gap (2 independent signals).", created_at: "2026-01-22T09:01:12Z" },
        { event_type: "RED_FLAG_RAISED", severity: "critical", message: "DataPulse AI: 6 churns, 80% cite competitor. Backlog at 116.", created_at: "2026-01-22T09:01:11Z" },
        { event_type: "ADVISOR_MATCH", severity: "warning", message: "Competitive Displacement Alert: 3-5 week churn wave expected. Engineering sprint critical.", created_at: "2026-01-22T09:01:09Z" },
        { event_type: "MEMORY_WRITTEN", severity: "info", message: "Memory page: 2026-W04 Competitive Displacement (4 chunks).", created_at: "2026-01-22T09:01:06Z" },
      ],
      deltas: { mrr_pct: -3.98, velocity_net: 28, backlog_delta: 28, confidence_delta: -0.13 },
      saved_mrr: { direct: { amount: 0, actions: 0, avg_confidence: null }, likely: { amount: 0, actions: 0, avg_confidence: null }, reported: { amount: 0, actions: 0, avg_confidence: null } },
      memory_health: { total_pages: 4, matches_found: 2, avg_relevance: 0.83, active_playbooks: 1, stale_playbooks: 0 },
      llm_provider: "Gemini 2.5 Flash",
      cross_model_consistency: 83,
    },
    memoryPages: [
      { id: "cl-w04", title: "2026-W04 Competitive Displacement Escalation", category: "churn_prevention", tags: ["churn", "mrr-decline", "red-flags", "feature-demand"], compiled_truth: "MRR declined 3.98% to $33,800. 6 churns — 80% cite DataPulse AI. Backlog at 116 (+28 this week). ESCALATION. GH-501 now critical.", created_at: "2026-01-22T09:01:06Z", metadata: { reporting_week: "2026-W04", confidence: 0.59 }, timeline: [{ event: "RISK_ESCALATION", detail: "Competitive churn acceleration + feature gap — 2 independent signals." }] },
      { id: "cl-w03", title: "2026-W03 Competitor Feature Launch", category: "churn_prevention", tags: ["churn", "feature-demand"], compiled_truth: "MRR declined 0.56% to $35,200. DataPulse AI shipped major AI feature. 6 accounts mention competitor. Feature backlog spiking. Competitive Displacement Alert triggered.", created_at: "2026-01-15T09:01:06Z", metadata: { reporting_week: "2026-W03", confidence: 0.72 }, timeline: [{ event: "CEO_RECOMMEND", detail: "Competitive Displacement Alert: feature gap now critical for retention." }] },
    ],
    attributionEntries: [],
  },

  /* ── 12. THE FREEMIUM TRAP ──────────────────────────────────────────────────── */
  {
    id: "freemium_trap",
    label: "The Freemium Trap",
    description: "High activation, near-zero paid conversion — unit economics collapse",
    badge: "risk",
    data: {
      reporting_week: "2026-W04",
      last_run: "2026-01-22T09:00:00Z",
      mrr: { current: 3000, previous: 2800, change_pct: 7.14 },
      active_subscriptions: 30,
      churn: { rate: 0.0, at_risk: 0, reason: "500 free users, 30 paid — 6% conversion rate. Usage high (68%) but conversion funnel broken. MRR growing slowly while free tier absorbing all value." },
      velocity: { opened: 18, closed: 15, net: 3, avg_close_hrs: 24.0, backlog: 28 },
      blocked: [],
      confidence: { current: 0.64, history: [0.72, 0.70, 0.68, 0.64] },
      red_flags: [
        { metric: "Conversion Funnel Broken", severity: "critical", detail: "500 free users, 6% paid conversion. Industry benchmark: 15-25%. Free tier absorbing full product value." },
        { metric: "Unit Economics Collapse", severity: "warning", detail: "CAC rising faster than ARPU. Rule of 40: -22. Free tier infrastructure cost exceeds paid revenue contribution." },
      ],
      skills: [
        { name: "saas_metrics_dashboard", tier: 0, agent: "CFO", status: "healthy", success_rate: 100 },
        { name: "unit_economics_rule40", tier: 0, agent: "CFO", status: "healthy", success_rate: 100 },
        { name: "freemium_conversion_alert", tier: 1, agent: "CEO", status: "healthy", success_rate: 71 },
        { name: "github_issue_auto_triage", tier: 1, agent: "PM", status: "healthy", success_rate: 94 },
      ],
      digests: [
        { period: "2026-W04", status: "delivered", channel: "slack" },
        { period: "2026-W03", status: "delivered", channel: "email" },
      ],
      cost: { last_run: 0.00035, monthly: 0.015, ceiling: 25.0 },
      recommendation: "ESCALATION: Conversion funnel failure + unit economics collapse (2 signals). Paid conversion at 6% (benchmark: 20%). Free users are getting full value without paying. Options: (1) move key features behind paywall, (2) add usage-based limits to free tier, (3) trigger paid upgrade at activation milestone. Recommend option 1 for fastest MRR impact.",
      advisor_note: "Freemium conversion trap: high feature adoption signals product-market fit but paywall positioning is broken. 500 free users = 500 potential paying customers. At 20% conversion = $3,000 additional MRR. Paywall repositioning typically requires 4-6 weeks to see conversion data. Start now.",
      advisor_confidence: 0.64,
      playbook_match: { name: "Freemium Conversion Alert", success_rate: 0.71, applications: 1, flag: "moderate" },
      unit_economics: { rule40_score: -22.0, health_grade: "Critical", ltv_simple: 900, arpu: 100.0, quick_ratio: 1.2, nrr_pct: 103.1 },
      triage: { total: 18, categories: { bug: 2, feature: 10, chore: 4, question: 2 }, priorities: { P0: 0, P1: 2, P2: 10, P3: 6 }, pending_review: 4 },
      audit_events: [
        { event_type: "RISK_ESCALATION", severity: "critical", message: "W04 escalation: conversion failure + unit economics collapse (2 signals).", created_at: "2026-01-22T09:01:12Z" },
        { event_type: "RED_FLAG_RAISED", severity: "critical", message: "500 free users, 6% conversion. Rule of 40: -22. Free tier unviable.", created_at: "2026-01-22T09:01:11Z" },
        { event_type: "ADVISOR_MATCH", severity: "warning", message: "Freemium Conversion Alert: paywall repositioning required.", created_at: "2026-01-22T09:01:09Z" },
        { event_type: "MEMORY_WRITTEN", severity: "info", message: "Memory page: 2026-W04 Freemium Trap (3 chunks).", created_at: "2026-01-22T09:01:06Z" },
      ],
      deltas: { mrr_pct: 7.14, velocity_net: 3, backlog_delta: 3, confidence_delta: -0.04 },
      saved_mrr: { direct: { amount: 0, actions: 0, avg_confidence: null }, likely: { amount: 0, actions: 0, avg_confidence: null }, reported: { amount: 0, actions: 0, avg_confidence: null } },
      memory_health: { total_pages: 4, matches_found: 1, avg_relevance: 0.76, active_playbooks: 1, stale_playbooks: 0 },
      llm_provider: "Gemini 2.5 Flash",
      cross_model_consistency: 86,
    },
    memoryPages: [
      { id: "ft-w04", title: "2026-W04 Freemium Trap Escalation", category: "churn_prevention", tags: ["red-flags"], compiled_truth: "MRR $3,000. 30 paid subs, 500 free users, 6% conversion. ESCALATION: conversion failure + unit economics collapse. Rule of 40: -22. Free tier absorbing all product value.", created_at: "2026-01-22T09:01:06Z", metadata: { reporting_week: "2026-W04", confidence: 0.64 }, timeline: [{ event: "RISK_ESCALATION", detail: "Freemium conversion failure — paywall repositioning required." }] },
      { id: "ft-w03", title: "2026-W03 Conversion Funnel Warning", category: "churn_prevention", tags: ["red-flags"], compiled_truth: "MRR $2,800. 28 paid subs, 400 free users, 7% conversion. Conversion declining while free tier growing. Unit economics deteriorating.", created_at: "2026-01-15T09:01:06Z", metadata: { reporting_week: "2026-W03", confidence: 0.68 }, timeline: [{ event: "CEO_RECOMMEND", detail: "Freemium Conversion Alert: free tier growth outpacing paid." }] },
    ],
    attributionEntries: [],
  },

  /* ── 13. THE ENTERPRISE PILOT ───────────────────────────────────────────────── */
  {
    id: "enterprise_pilot",
    label: "The Enterprise Pilot",
    description: "Single pilot distorts metrics — conversion tracked through W8 renewal",
    badge: "risk",
    data: {
      reporting_week: "2026-W08",
      last_run: "2026-02-19T09:00:00Z",
      mrr: { current: 22800, previous: 21800, change_pct: 4.59 },
      active_subscriptions: 60,
      churn: { rate: 0.0, at_risk: 0, reason: "Axiom Systems pilot converted to paid ($12,000/mo). SSO integration resolved. Multi-stakeholder anchor confirmed." },
      velocity: { opened: 16, closed: 16, net: 0, avg_close_hrs: 28.0, backlog: 46 },
      blocked: [],
      confidence: { current: 0.86, history: [0.79, 0.76, 0.72, 0.68, 0.65, 0.67, 0.72, 0.86] },
      red_flags: [],
      skills: [
        { name: "saas_metrics_dashboard", tier: 0, agent: "CFO", status: "healthy", success_rate: 100 },
        { name: "enterprise_pilot_tracker", tier: 1, agent: "CEO", status: "healthy", success_rate: 88 },
        { name: "concentration_risk_alert", tier: 1, agent: "CEO", status: "healthy", success_rate: 84 },
        { name: "weekly_digest_delivery", tier: 1, agent: "CEO", status: "healthy", success_rate: 100 },
      ],
      digests: [
        { period: "2026-W08", status: "delivered", channel: "slack" },
        { period: "2026-W07", status: "delivered", channel: "email" },
      ],
      cost: { last_run: 0.00038, monthly: 0.016, ceiling: 25.0 },
      recommendation: "Axiom Systems pilot converted to $12,000/mo paid contract. SSO (GH-701) resolved in time. Multi-stakeholder engagement (3 champions) confirmed. Concentration risk remains: Axiom = 53% of MRR. Recommend: (1) activate pipeline diversification — 3 enterprise prospects identified, (2) Axiom success story as case study for outbound.",
      advisor_note: "Pilot conversion playbook executed correctly: multi-stakeholder anchoring, SSO delivered before renewal deadline, 60-day evaluation window honoured. W4 escalation (pilot dependency + renewal timeline) was the correct intervention point. Concentration risk now requires 90-day mitigation plan.",
      advisor_confidence: 0.86,
      playbook_match: { name: "Enterprise Pilot Tracker", success_rate: 0.88, applications: 1, flag: "strong" },
      unit_economics: { rule40_score: 29.6, health_grade: "Strong", ltv_simple: 5700, arpu: 380.0, quick_ratio: 3.2, nrr_pct: 108.6 },
      triage: { total: 16, categories: { bug: 2, feature: 6, chore: 6, question: 2 }, priorities: { P0: 0, P1: 1, P2: 8, P3: 7 }, pending_review: 2 },
      audit_events: [
        { event_type: "EXPANSION_TRIGGERED", severity: "info", message: "Axiom Systems converted to paid: $12,000/mo — pilot success.", created_at: "2026-02-19T09:01:12Z" },
        { event_type: "OUTCOME_RECORDED", severity: "info", message: "Enterprise Pilot playbook: conversion confirmed. SSO resolved W07.", created_at: "2026-02-19T09:01:10Z" },
        { event_type: "CONFIDENCE_RECORDED", severity: "info", message: "CEO confidence: 0.86 — pilot conversion resolved dependency risk.", created_at: "2026-02-19T09:01:08Z" },
        { event_type: "MEMORY_WRITTEN", severity: "info", message: "Memory page: 2026-W08 Enterprise Pilot Conversion (4 chunks).", created_at: "2026-02-19T09:01:06Z" },
      ],
      deltas: { mrr_pct: 4.59, velocity_net: 0, backlog_delta: -2, confidence_delta: 0.14 },
      saved_mrr: {
        direct: { amount: 12000, actions: 1, avg_confidence: 0.96 },
        likely: { amount: 0, actions: 0, avg_confidence: null },
        reported: { amount: 0, actions: 0, avg_confidence: null },
      },
      memory_health: { total_pages: 8, matches_found: 3, avg_relevance: 0.89, active_playbooks: 2, stale_playbooks: 0 },
      llm_provider: "Gemini 2.5 Flash",
      cross_model_consistency: 92,
    },
    memoryPages: [
      { id: "ep-w08", title: "2026-W08 Enterprise Pilot Conversion", category: "expansion", tags: ["mrr-growth", "playbook:Expansion Revenue"], compiled_truth: "MRR rose 4.59% to $22,800. Axiom Systems converted: $12,000/mo paid. SSO resolved. Multi-stakeholder confirmed. Confidence: 0.86.", created_at: "2026-02-19T09:01:06Z", metadata: { reporting_week: "2026-W08", confidence: 0.86 }, timeline: [{ event: "EXPANSION_TRIGGERED", detail: "Axiom Systems pilot → paid: $12,000/mo." }] },
      { id: "ep-w04", title: "2026-W04 Pilot Dependency Escalation", category: "churn_prevention", tags: ["churn", "red-flags"], compiled_truth: "MRR $22,600. Axiom pilot = 53% of MRR. Renewal timeline compressing. ESCALATION — single-account dependency + renewal pressure (2 signals). SSO GH-701 critical path.", created_at: "2026-01-22T09:01:06Z", metadata: { reporting_week: "2026-W04", confidence: 0.68 }, timeline: [{ event: "RISK_ESCALATION", detail: "Pilot dependency + renewal timeline — 2 independent signals." }] },
      { id: "ep-w03", title: "2026-W03 Pilot Goes Live", category: "reporting", tags: [], compiled_truth: "MRR $22,600 (Axiom live). Metrics distorted — 53% of MRR from single pilot. System correctly identified distortion and avoided false confidence.", created_at: "2026-01-15T09:01:06Z", metadata: { reporting_week: "2026-W03", confidence: 0.72 }, timeline: [{ event: "CEO_RECOMMEND", detail: "Concentration Risk Alert — pilot distorts aggregate metrics." }] },
    ],
    attributionEntries: [
      { id: "ep-a1", week: "2026-W08", attribution_tier: "direct", mrr_amount: 12000, action_id: "ep-w08-d1", evidence: { confidence: 0.96, action: "Enterprise pilot converted to paid — SSO delivered, multi-stakeholder secured", playbook: "Enterprise Pilot Tracker" } },
    ],
  },

  /* ── 14. THE FOUNDER BURNOUT ────────────────────────────────────────────────── */
  {
    id: "founder_burnout",
    label: "The Founder Burnout",
    description: "Solo-founder velocity collapse — existential SPOF escalation at W5",
    badge: "engineering",
    data: {
      reporting_week: "2026-W05",
      last_run: "2026-01-29T09:00:00Z",
      mrr: { current: 6600, previous: 6700, change_pct: -1.49 },
      active_subscriptions: 34,
      churn: { rate: 0.03, at_risk: 3, reason: "0 GitHub commits in 10 days. 5 support tickets unanswered >7 days. Founder is sole engineer — existential single point of failure." },
      velocity: { opened: 3, closed: 0, net: 3, avg_close_hrs: 240.0, backlog: 27 },
      blocked: [],
      confidence: { current: 0.52, history: [0.82, 0.80, 0.74, 0.68, 0.52] },
      red_flags: [
        { metric: "Velocity Collapse", severity: "critical", detail: "0 issues closed this week. 10 days with zero commits. Avg close time: 240h." },
        { metric: "Founder SPOF", severity: "critical", detail: "Sole engineer absent. Support backlog growing — customers noticing. Existential business risk." },
      ],
      skills: [
        { name: "saas_metrics_dashboard", tier: 0, agent: "CFO", status: "healthy", success_rate: 100 },
        { name: "velocity_drop_alert", tier: 1, agent: "PM", status: "healthy", success_rate: 82 },
        { name: "founder_spof_detection", tier: 1, agent: "CEO", status: "healthy", success_rate: 90 },
        { name: "weekly_digest_delivery", tier: 1, agent: "CEO", status: "healthy", success_rate: 100 },
      ],
      digests: [
        { period: "2026-W05", status: "delivered", channel: "slack" },
        { period: "2026-W04", status: "delivered", channel: "email" },
      ],
      cost: { last_run: 0.00031, monthly: 0.013, ceiling: 25.0 },
      recommendation: "ESCALATION: Velocity collapse alone (solo-founder SPOF rule). 0 commits in 10 days, 0 issues closed. This is NOT a normal backlog situation — a solo founder going dark represents existential risk. Immediate actions: (1) hire contract engineer for 30-day coverage, (2) auto-respond to support tickets with honest status update, (3) founder: document bus-factor critical systems today.",
      advisor_note: "System correctly escalated on velocity collapse alone (no paired churn signal yet) — solo-founder SPOF is an escalation trigger independent of churn. Historical pattern: founders who go dark for 10+ days without explanation have 80% chance of continued absence for 3+ more weeks. Early contractor hire reduces churn damage by 60%.",
      advisor_confidence: 0.52,
      playbook_match: { name: "Velocity Drop Alert", success_rate: 0.82, applications: 3, flag: "strong" },
      unit_economics: { rule40_score: 1.5, health_grade: "Adequate", ltv_simple: 1980, arpu: 194.1, quick_ratio: 0.9, nrr_pct: 95.5 },
      triage: { total: 3, categories: { bug: 2, feature: 0, chore: 1, question: 0 }, priorities: { P0: 1, P1: 2, P2: 0, P3: 0 }, pending_review: 0 },
      audit_events: [
        { event_type: "RISK_ESCALATION", severity: "critical", message: "W05 escalation: velocity collapse alone — solo-founder SPOF (existential risk rule).", created_at: "2026-01-29T09:01:12Z" },
        { event_type: "RED_FLAG_RAISED", severity: "critical", message: "0 commits in 10 days. 0 issues closed. 5 support tickets >7 days old.", created_at: "2026-01-29T09:01:11Z" },
        { event_type: "ADVISOR_MATCH", severity: "warning", message: "Velocity Drop Alert: solo-founder absence = existential SPOF. Contractor required.", created_at: "2026-01-29T09:01:09Z" },
        { event_type: "MEMORY_WRITTEN", severity: "info", message: "Memory page: 2026-W05 Founder Burnout Escalation (3 chunks).", created_at: "2026-01-29T09:01:06Z" },
      ],
      deltas: { mrr_pct: -1.49, velocity_net: 3, backlog_delta: 3, confidence_delta: -0.16 },
      saved_mrr: { direct: { amount: 0, actions: 0, avg_confidence: null }, likely: { amount: 0, actions: 0, avg_confidence: null }, reported: { amount: 0, actions: 0, avg_confidence: null } },
      memory_health: { total_pages: 5, matches_found: 2, avg_relevance: 0.80, active_playbooks: 1, stale_playbooks: 0 },
      llm_provider: "Gemini 2.5 Flash",
      cross_model_consistency: 81,
    },
    memoryPages: [
      { id: "fb-w05", title: "2026-W05 Founder Burnout Escalation", category: "engineering", tags: ["low-velocity", "red-flags"], compiled_truth: "MRR declined 1.49% to $6,600. 0 commits in 10 days. 0 issues closed. 23 support tickets. ESCALATION on velocity collapse alone (SPOF rule). Confidence: 0.52.", created_at: "2026-01-29T09:01:06Z", metadata: { reporting_week: "2026-W05", confidence: 0.52 }, timeline: [{ event: "RISK_ESCALATION", detail: "Velocity collapse — solo-founder SPOF escalation." }] },
      { id: "fb-w04", title: "2026-W04 Velocity Near-Zero", category: "engineering", tags: ["low-velocity"], compiled_truth: "MRR flat at $6,700. Velocity: 1 closed / 4 opened. Avg close time: 120h. 2 support tickets unanswered. No external blocker identified.", created_at: "2026-01-22T09:01:06Z", metadata: { reporting_week: "2026-W04", confidence: 0.68 }, timeline: [{ event: "CEO_RECOMMEND", detail: "Velocity Drop Alert: near-zero shipping — watch for SPOF signal." }] },
      { id: "fb-w03", title: "2026-W03 First Velocity Drop", category: "engineering", tags: ["low-velocity"], compiled_truth: "MRR rose 1.52% to $6,700. Velocity: 2 closed / 6 opened. Avg close time: 72h. Support tickets at 11. Velocity Drop Alert triggered.", created_at: "2026-01-15T09:01:06Z", metadata: { reporting_week: "2026-W03", confidence: 0.74 }, timeline: [{ event: "CEO_RECOMMEND", detail: "First velocity drop — monitoring." }] },
    ],
    attributionEntries: [],
  },

  /* ── 15. THE SEASONAL CLIFF ─────────────────────────────────────────────────── */
  {
    id: "seasonal_cliff",
    label: "The Seasonal Cliff",
    description: "Predictable Q4 SMB decline — memory suppresses false escalation",
    badge: "stable",
    data: {
      reporting_week: "2026-W10",
      last_run: "2026-03-05T09:00:00Z",
      mrr: { current: 41200, previous: 42200, change_pct: -2.37 },
      active_subscriptions: 212,
      churn: { rate: 0.02, at_risk: 8, reason: "Q4 seasonal cliff — mid-November SMB budget freeze. Cancellations cite 'budget freeze until January' not dissatisfaction. Matches prior-year pattern." },
      velocity: { opened: 15, closed: 16, net: -1, avg_close_hrs: 31.0, backlog: 61 },
      blocked: [],
      confidence: { current: 0.74, history: [0.82, 0.83, 0.84, 0.84, 0.83, 0.81, 0.77, 0.75, 0.74, 0.74] },
      red_flags: [
        { metric: "Seasonal Decline Active", severity: "warning", detail: "MRR down 2.37% — Q4 SMB holiday slowdown. NOT pathological churn. Prior-year same week: -2.1%." },
      ],
      skills: [
        { name: "saas_metrics_dashboard", tier: 0, agent: "CFO", status: "healthy", success_rate: 100 },
        { name: "seasonal_churn_watch", tier: 1, agent: "CEO", status: "healthy", success_rate: 86 },
        { name: "unit_economics_rule40", tier: 0, agent: "CFO", status: "healthy", success_rate: 100 },
        { name: "weekly_digest_delivery", tier: 1, agent: "CEO", status: "healthy", success_rate: 100 },
      ],
      digests: [
        { period: "2026-W10", status: "delivered", channel: "slack" },
        { period: "2026-W09", status: "delivered", channel: "email" },
        { period: "2026-W08", status: "delivered", channel: "slack" },
      ],
      cost: { last_run: 0.00035, monthly: 0.015, ceiling: 25.0 },
      recommendation: "Seasonal Churn Watch playbook active — no escalation warranted. Decline matches Q4 pattern from prior-year memory (W07-W11: -8% cumulative, recovers W12-W13). Actions: (1) pre-write Q1 win-back campaign now for January deployment, (2) use downtime to ship deferred backlog items, (3) track accounts citing 'budget' vs 'dissatisfaction' — different intervention strategies.",
      advisor_note: "Memory vault confirms: Q4 seasonal pattern present in prior-year data. W07-W11 declines are expected (-6-8% cumulative), Q1 recovery follows reliably. System correctly NOT escalating — this is a known pattern, not a churn spiral. False escalation suppressed by memory context.",
      advisor_confidence: 0.74,
      playbook_match: { name: "Seasonal Churn Watch", success_rate: 0.86, applications: 2, flag: "strong" },
      unit_economics: { rule40_score: 31.6, health_grade: "Strong", ltv_simple: 10300, arpu: 194.3, quick_ratio: 2.2, nrr_pct: 97.8 },
      triage: { total: 15, categories: { bug: 3, feature: 5, chore: 5, question: 2 }, priorities: { P0: 0, P1: 1, P2: 6, P3: 8 }, pending_review: 2 },
      audit_events: [
        { event_type: "RUN_COMPLETE", severity: "info", message: "Weekly run W10 completed. MRR: $41,200 (-2.37%). Seasonal pattern confirmed — no escalation.", created_at: "2026-03-05T09:01:12Z" },
        { event_type: "ADVISOR_MATCH", severity: "info", message: "Seasonal Churn Watch: prior-year Q4 pattern matched. False escalation suppressed.", created_at: "2026-03-05T09:01:10Z" },
        { event_type: "MEMORY_WRITTEN", severity: "info", message: "Memory page: 2026-W10 Seasonal Cliff (3 chunks, pattern confirmed).", created_at: "2026-03-05T09:01:08Z" },
        { event_type: "CONFIDENCE_RECORDED", severity: "info", message: "CEO confidence: 0.74 — seasonal context reduces uncertainty.", created_at: "2026-03-05T09:01:06Z" },
      ],
      deltas: { mrr_pct: -2.37, velocity_net: -1, backlog_delta: -1, confidence_delta: 0.00 },
      saved_mrr: { direct: { amount: 0, actions: 0, avg_confidence: null }, likely: { amount: 0, actions: 0, avg_confidence: null }, reported: { amount: 0, actions: 0, avg_confidence: null } },
      memory_health: { total_pages: 10, matches_found: 3, avg_relevance: 0.88, active_playbooks: 1, stale_playbooks: 0 },
      llm_provider: "Gemini 2.5 Flash",
      cross_model_consistency: 89,
    },
    memoryPages: [
      { id: "sl-w10", title: "2026-W10 Seasonal Cliff — Bottom", category: "retention", tags: ["churn", "mrr-decline"], compiled_truth: "MRR declined 2.37% to $41,200. Q4 seasonal cliff bottom — 8 at-risk accounts citing budget freeze. System correctly matched prior-year pattern. No escalation. Confidence: 0.74.", created_at: "2026-03-05T09:01:06Z", metadata: { reporting_week: "2026-W10", confidence: 0.74 }, timeline: [{ event: "ADVISOR_MATCH", detail: "Prior-year Q4 pattern confirmed — false escalation suppressed." }] },
      { id: "sl-w09", title: "2026-W09 Seasonal Decline Deepens", category: "retention", tags: ["churn", "mrr-decline"], compiled_truth: "MRR declined 2.09% to $42,200. Mid-Q4. Cancellations cite 'budget freeze until January'. Seasonal Churn Watch active.", created_at: "2026-02-26T09:01:06Z", metadata: { reporting_week: "2026-W09", confidence: 0.74 }, timeline: [{ event: "CEO_RECOMMEND", detail: "Seasonal decline deepening — within expected range." }] },
      { id: "sl-w08", title: "2026-W08 Q4 Seasonal Start", category: "retention", tags: ["churn"], compiled_truth: "MRR declined 1.82% to $43,100. Q4 seasonal slowdown beginning. 4 churns citing holiday budget freeze. Pattern watch triggered.", created_at: "2026-02-19T09:01:06Z", metadata: { reporting_week: "2026-W08", confidence: 0.75 }, timeline: [{ event: "CEO_RECOMMEND", detail: "Seasonal Churn Watch: Q4 pattern starting — check prior-year memory." }] },
      { id: "sl-w07", title: "2026-W07 Seasonal Signal First Detected", category: "retention", tags: ["churn"], compiled_truth: "MRR declined 1.35% to $43,900. First seasonal signal — 3 SMB cancellations citing budget. Advisor cited prior-year Q4 pattern. No escalation.", created_at: "2026-02-12T09:01:06Z", metadata: { reporting_week: "2026-W07", confidence: 0.77 }, timeline: [{ event: "ADVISOR_MATCH", detail: "Prior-year Q4 seasonal pattern cited — do not escalate." }] },
      { id: "sl-w04", title: "2026-W04 Q3 Peak", category: "expansion", tags: ["mrr-growth"], compiled_truth: "MRR rose 1.39% to $43,700. Q3 peak — consistent expansion. 222 subs. No seasonal signals.", created_at: "2026-01-22T09:01:06Z", metadata: { reporting_week: "2026-W04", confidence: 0.84 }, timeline: [{ event: "RUN_COMPLETE", detail: "Q3 peak — consistent growth." }] },
    ],
    attributionEntries: [],
  },
];

/* Default scenario index — Growth Stage is scenario index 2 (Growth Rocket)
   but we'll use a dedicated "Growth Stage" as the default (index 2 = growth_rocket
   is closest; in demo the original MOCK_DATA is scenario index 2).
   Export the default scenario index for initial state. */
export const DEFAULT_SCENARIO_INDEX = 2; // The Growth Rocket as a reasonable default
